name: docker build
on:
  push:
    branches:
      - "kaigionrails"
  pull_request:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: false
